### ISSUE TITLE
wrong ram detect

### ISSUE THREAD

**Issue by CalibenQC** [armbian/community#11]
I have Pine Quartz64a with 8 GB of ram and the os doesn't detect the 8 GB only 2 like in the screenshot
![Screenshot_44](https://user-images.githubusercontent.com/27741688/211179301-0778bfed-d8fc-44f2-bec9-bb2476da7b84.png)
It the same with Jammy release

**Comment by igorpecovnik** [comment]
> in the screenshot

... "No end-user support". In case you are a business user, start [here](https://forum.armbian.com/subscriptions).

Otherwise please report a problem here: https://bugzilla.kernel.org/

Thank you for your understanding.

**Comment by CalibenQC** [comment]
i juste leaving a feed back for a future update
